version: '3'
services:
  redis:
    image: "bitnami/redis:latest"
    platform: linux/amd64
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  db:
    image: debezium/example-postgres
    platform: linux/amd64
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: toor
    ports:
      - 5432:5432
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"

  adminer:
    image: adminer
    platform: linux/amd64
    restart: always
    ports:
      - 8001:8080  # Adminer'a disaridan erisim saglar.